title: Yong Zhang
description: Ebaas is an enterprise application platform. It supports a no-code and metadata-driven development approach that enables professional and nonprofessional developers to rapidly build single page applications 

url: https://ebaas.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Download
   url: /download
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: ebaas
   twitter: johnzhang3400
   facebook: yongzhang
   email: yongz@yahoo.com.com

google_analytics: "UA-58263416-1"

gems:
  - jekyll-seo-tag
