title: Yong Zhang Personal Site
description: Ebaas, an enterprise application for test data management. ML Studio, a development tool for Machine Learning

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Download
   url: /download
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: yongz@yahoo.com.com

google_analytics: "UA-58263416-1"

gems:
  - jekyll-seo-tag
