title: Ebaas
description: Ebaas is an enterprise application platform. It supports a no-code and metadata-driven development approach that enables professional and nonprofessional developers to rapidly build single page applications 

url: https://smarttdm.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 15

navigation:
 - title: 首页
   url: /index.html

social:
   github: ebaas

google_analytics: "UA-58263416-1"

gems:
  - jekyll-seo-tag
